"""Keyword-triggered SFX detection, timed to real per-word timestamps, for
all 6 channels.

Categories/keyword starting points, minimum-gap value, and cascade-only-
on-final-word rule are transcribed from the user's own request -- product
requirements, not audio-engineering facts to verify against real repos.
BUT the user also asked to verify/expand each channel's keyword list
against real content this repo has actually produced before finalizing --
that check happened, and it changed things. Real content checked:
- `src/pipeline/channelConfigs.ts` (scriptTone/beatTypes per channel)
- `pipeline/footage_sourcing/sample_beats.py` (5 beats/channel) -- NOTE:
  that file's own docstring says these are "hand-authored TEST FIXTURES,
  not LLM output." No channel in this repo has ever had a script actually
  generated by an LLM (keyword_extraction.py is still stub-gated, no
  provider key). So "real content this pipeline has actually produced" is,
  as of this session, these hand-authored fixtures plus
  `pipeline/ch6_short_001.py`'s 26-beat CH6 script -- not pipeline output
  in the sense the request implied. Used as the best real reference
  available, with that caveat stated plainly rather than silently treated
  as more authoritative than it is.

Findings from that check, per channel:
- CH1: proposed keywords (dopamine/addicted/craving/urge/habit) do NOT
  appear anywhere in the 5 real sample beats. "brain" does appear once.
  Kept the proposed list (channel is literally named after dopamine, and
  beatTypes includes "stat" supporting the STUDY_STAT category even though
  no percentage appears in this small sample) and ADDED "brain", "loop",
  "notification" since those are the words actually used.
- CH3: "leaked" and "expose" (not "exposed") appear in real content.
  "classified"/"redacted"/"declassified"/"secret" don't appear in this
  5-beat sample but the channel's own name and stated niche
  ("declassified history") support keeping them. Added "expose" alongside
  "exposed".
- CH4: proposed keywords (neurons/synapse/cortex/signal/neural) appear
  ZERO times in CH4's real sample content, which instead says "brain" and
  "mind" -- the same word CH1 uses. Without adding these, CH4's own actual
  existing sample beats would NEVER fire NEURO_TERM at all. Added "brain"
  and "mind" to CH4's list. This does NOT collapse CH1/CH4 into one sound
  -- classification is scoped per-channel (a CH1 beat saying "brain" fires
  CH1's cue; a CH4 beat saying "brain" fires CH4's cue), only the
  resulting AUDIO differs, which is exactly what makes them sound
  different from each other despite overlapping vocabulary.
- CH5: year mentions ("1943", "1977") and "died" are confirmed real.
  "war"/"empire"/"discovered" don't appear in the 5-beat sample; kept as
  plausible for a history channel, not confirmed.
- CH6: "miles" (not "miles away" specifically -- real text says "five
  hundred million miles") and "telescope" are confirmed real (checked
  against both the 5-beat sample AND the fuller 26-beat
  ch6_short_001.py script). "light-year"/"kilometers away"/"explosion"/
  "collide"/"black hole"/"gravity"/"discovered"/"NASA" appear in NEITHER
  real CH6 script (both are Jupiter/Great-Red-Spot-focused, no black-hole
  or collision content yet) -- kept as proposed since they're clearly
  on-topic for a "Red Space Facts" channel's future broader content, but
  flagged as unconfirmed by anything actually produced so far.
- CH2: unchanged, already verified against real content in a prior pass.

NOT SOURCED, FLAGGED AGAIN PER THE USER'S OWN INSTRUCTION: no SFX asset
library exists anywhere in this repo (re-confirmed by `find` before
writing this). Checked three more potential real sources this pass
(freesound.org, pixabay.com, mixkit.co) -- all three blocked by this
session's egress policy (403 on the CONNECT tunnel, same class of denial
as NASA/Wikimedia/HuggingFace). Placeholder tones below remain
synthesized, not real, and are now more varied (tones/sweeps/noise
bursts) so channels are audibly distinguishable from each other, but they
are still not real SFX and must not be mistaken for them.

Also NOT SOURCED: the request says to "normalize any new asset with the
same dynaudnorm ... settings you already applied to the existing
library." No dynaudnorm or other one-shot normalization was applied to
the original placeholder tones -- "SFX one-shot normalization target" was
explicitly flagged NOT_SOURCED in the prior pass (see CLAUDE.md), and
remains so; no real value was found this pass either. There is no prior
setting to replicate. All placeholder tones (old and new) ARE built via
the same generation approach (fixed peak amplitude at synthesis, fixed
fade shape per type) so they're level-matched to each other by
construction, which is what's actually true -- not overstated as
"normalized with sourced settings" when it isn't.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from enum import IntEnum
from pathlib import Path

from .ffmpeg_bin import ffmpeg_path
from ..footage_sourcing.types import ChannelId
from ..shot_brief import Beat

MIN_GAP_MS = 175  # midpoint of the user's specified 150-200ms range; not
# independently sourced from a bible or repo -- the user asked for
# "minimum 150-200ms," not one exact number, so this is a documented choice
# within that range, not outside it.


class SfxCategory(IntEnum):
    """Priority tiers -- lower value = higher priority, per the user's
    original rule ("money/number > generic"), generalized to 6 channels:
    cascade payoff > this channel's primary topic category > this
    channel's secondary topic category > twist > hook-opener. Cross-
    channel comparisons never actually happen (detect_triggers is always
    scoped to one channel), so channel-specific categories only need to be
    correctly ordered relative to each OTHER category that same channel
    can produce, not globally unique."""

    CASCADE_PAYOFF = 0  # universal -- cascade-beat final-word/phrase-hold hit

    # Tier 1: each channel's primary topic category
    MONEY = 10  # CH2
    PSYCHOLOGY_TERM = 11  # CH1
    CLASSIFIED = 12  # CH3
    NEURO_TERM = 13  # CH4
    DATE_EVENT = 14  # CH5
    SCALE_DISTANCE = 15  # CH6

    # Tier 2: each channel's secondary topic category
    STUDY_STAT = 20  # CH1
    COVERUP = 21  # CH3
    MEMORY = 22  # CH4
    LOST_TO_HISTORY = 23  # CH5
    DISCOVERY = 24  # CH6

    # Universal, lowest priority
    TWIST = 30
    HOOK_OPENER = 40


# Per-channel keyword -> category. See module docstring for what's
# confirmed-real vs. proposed-but-unconfirmed per channel.
_CHANNEL_KEYWORDS: dict[ChannelId, dict[SfxCategory, set[str]]] = {
    ChannelId.CH1: {
        SfxCategory.PSYCHOLOGY_TERM: {
            "dopamine", "addicted", "craving", "urge", "habit",
            "brain", "loop", "notification",  # added: confirmed real usage
        },
        SfxCategory.STUDY_STAT: {"study", "researchers", "%", "percent"},
    },
    ChannelId.CH2: {
        SfxCategory.MONEY: {
            "$", "dollar", "dollars", "million", "millions", "billion", "billions",
            "cost", "price", "paid", "worth", "richest", "fortune",
        },
    },
    ChannelId.CH3: {
        SfxCategory.CLASSIFIED: {
            "classified", "redacted", "declassified", "secret", "leaked",
            "exposed", "expose",  # "expose" added: real usage is "expose", not "exposed"
        },
        SfxCategory.COVERUP: {"cover-up", "coverup", "hidden", "buried"},
    },
    ChannelId.CH4: {
        SfxCategory.NEURO_TERM: {
            "neurons", "neuron", "synapse", "cortex", "signal", "neural",
            "brain", "mind",  # added: this channel's REAL content uses these, not the clinical terms
        },
        SfxCategory.MEMORY: {"memory", "forget", "forgot", "recall"},
    },
    ChannelId.CH5: {
        # DATE_EVENT also matches 4-digit years via regex, handled in _classify
        SfxCategory.DATE_EVENT: {"died", "war", "empire", "discovered", "discovery"},
        SfxCategory.LOST_TO_HISTORY: {"forgotten", "vanished"},  # "lost to history" handled as phrase below
    },
    ChannelId.CH6: {
        SfxCategory.SCALE_DISTANCE: {
            "light-year", "light-years", "miles", "kilometers", "explosion",
            "collide", "collision", "gravity",
        },
        # "black hole" is a phrase, handled below. "discovery" added
        # alongside "discovered" -- found the gap by testing "a discovery
        # that changed everything" and it not firing.
        SfxCategory.DISCOVERY: {"discovered", "discovery", "nasa", "telescope"},
    },
}

_YEAR_RE = re.compile(r"^(1[5-9]|20)\d{2}$")  # 1500-2099, generous enough for any real/history year mention
_PHRASE_TRIGGERS: dict[ChannelId, dict[SfxCategory, list[str]]] = {
    ChannelId.CH3: {SfxCategory.COVERUP: ["cover-up", "covered up"]},
    ChannelId.CH5: {SfxCategory.LOST_TO_HISTORY: ["lost to history"]},
    ChannelId.CH6: {SfxCategory.SCALE_DISTANCE: ["black hole", "miles away", "kilometers away"]},
}

_TWIST_KEYWORDS = {"but", "then", "immediately", "suddenly"}
_HOOK_OPENER_KEYWORDS = {"what", "why", "how", "did", "do", "does", "imagine"}


@dataclass(frozen=True)
class WordTiming:
    word: str
    start_frame: int


@dataclass(frozen=True)
class SfxTrigger:
    category: SfxCategory
    word: str
    frame: int
    channel_flavor: str


def _normalize(word: str) -> str:
    return re.sub(r"[^\w$%-]", "", word).lower()


def _channel_flavor(channel: ChannelId) -> str:
    """Per-channel variant selection. NOT bible-sourced -- new design work,
    using channelConfigs.ts's existing `scriptTone` strings as the "genre/
    mood config" the user referred to, since that's the only per-channel
    tone/genre data that already exists in this repo. Simple keyword match
    against the tone description; not a confirmed taxonomy."""
    tones = {
        ChannelId.CH1: "punchy, direct, mind-bending",
        ChannelId.CH2: "analytical, shocking, authoritative",
        ChannelId.CH3: "conspiratorial, terse, urgent",
        ChannelId.CH4: "scientific, vivid, revelatory",
        ChannelId.CH5: "measured, evocative, archival",
        ChannelId.CH6: "awe-inspiring, precise, cosmic",
    }
    tone = tones.get(channel, "")
    if "punchy" in tone or "shocking" in tone or "urgent" in tone:
        return "snappy"
    if "cosmic" in tone or "measured" in tone or "archival" in tone:
        return "deep"
    return "neutral"


def detect_triggers(
    beat: Beat,
    word_timings: list[WordTiming],
    channel: ChannelId,
    *,
    cascade_final_frame: int | None = None,
) -> list[SfxTrigger]:
    """Scans a beat's words for this CHANNEL's trigger keywords (plus the
    universal twist/hook-opener categories).

    For cascade beats, per the user's explicit rule ("SFX hit only on the
    final word/phrase-hold, not every hard-cut word"), this only considers
    the beat's FULL TEXT for a keyword match and -- if found -- fires
    exactly once, at `cascade_final_frame` (the phrase-hold start), never
    per-word. A cascade beat's match always reports CASCADE_PAYOFF
    (highest priority), regardless of which channel keyword matched,
    since the cascade final-word moment IS the big-reveal beat.
    """
    flavor = _channel_flavor(channel)

    if beat.cascade:
        if cascade_final_frame is None:
            raise ValueError("cascade_final_frame is required for cascade beats")
        full_text_words = {_normalize(w) for w in beat.text.split()}
        category = _classify(full_text_words, beat.text, channel)
        if category is None:
            return []
        return [
            SfxTrigger(
                category=SfxCategory.CASCADE_PAYOFF,
                word=beat.text,
                frame=cascade_final_frame,
                channel_flavor=flavor,
            )
        ]

    triggers: list[SfxTrigger] = []
    matched_word_indices: set[int] = set()

    # Multi-word phrase triggers first ("cover-up", "black hole", "lost to
    # history"...) -- these need a sliding window across word_timings,
    # since a single-word scan can never see "lost" + "to" + "history" as
    # one unit. Found this gap while implementing the per-word path below;
    # fixed here rather than left silently broken for non-cascade beats.
    for category, phrases in _PHRASE_TRIGGERS.get(channel, {}).items():
        for phrase in phrases:
            phrase_words = phrase.split()
            n = len(phrase_words)
            for i in range(len(word_timings) - n + 1):
                window = [_normalize(word_timings[i + j].word) for j in range(n)]
                if window == phrase_words:
                    triggers.append(
                        SfxTrigger(category=category, word=phrase, frame=word_timings[i].start_frame, channel_flavor=flavor)
                    )
                    matched_word_indices.update(range(i, i + n))

    for idx, wt in enumerate(word_timings):
        if idx in matched_word_indices:
            continue  # already covered by a phrase match above
        norm = _normalize(wt.word)
        category = _classify({norm}, wt.word, channel)
        if category is not None:
            triggers.append(SfxTrigger(category=category, word=wt.word, frame=wt.start_frame, channel_flavor=flavor))
    return triggers


def _classify(normalized_words: set[str], raw_text: str, channel: ChannelId) -> SfxCategory | None:
    raw_lower = raw_text.lower()

    channel_cats = _CHANNEL_KEYWORDS.get(channel, {})
    # Tier 1 then tier 2, in priority order, checking this channel's own categories only.
    for category, keywords in sorted(channel_cats.items(), key=lambda kv: kv[0]):
        if "$" in raw_text and "$" in keywords:
            return category
        if normalized_words & keywords:
            return category

    for category, phrases in _PHRASE_TRIGGERS.get(channel, {}).items():
        if any(p in raw_lower for p in phrases):
            return category

    if channel == ChannelId.CH5:
        for w in normalized_words:
            if _YEAR_RE.match(w):
                return SfxCategory.DATE_EVENT

    if normalized_words & _TWIST_KEYWORDS:
        return SfxCategory.TWIST
    if normalized_words & _HOOK_OPENER_KEYWORDS:
        return SfxCategory.HOOK_OPENER
    return None


def resolve_conflicts(triggers: list[SfxTrigger], fps: int, min_gap_ms: int = MIN_GAP_MS) -> list[SfxTrigger]:
    """Enforces the minimum gap between cues; when two triggers land within
    the gap, keeps only the higher-priority one (lower SfxCategory value)."""
    min_gap_frames = round(min_gap_ms / 1000 * fps)
    ordered = sorted(triggers, key=lambda t: t.frame)

    kept: list[SfxTrigger] = []
    for trigger in ordered:
        conflict_idx = None
        for i, existing in enumerate(kept):
            if abs(trigger.frame - existing.frame) < min_gap_frames:
                conflict_idx = i
                break
        if conflict_idx is None:
            kept.append(trigger)
            continue
        if trigger.category < kept[conflict_idx].category:  # lower value = higher priority
            kept[conflict_idx] = trigger
    return sorted(kept, key=lambda t: t.frame)


# --- Placeholder tones -- NOT real SFX, see module docstring ---
#
# Three generator "shapes" so categories are audibly distinguishable, not
# just different pitches of the same beep:
#   "tone"  -- a sine at a fixed frequency (original approach)
#   "sweep" -- aevalsrc chirp, frequency rises or falls linearly over the
#              cue's duration (genuine riser/reverse-riser, not simulated)
#   "burst" -- bandpassed white noise (anoisesrc + bandpass), for
#              paper/static/rumble-ish textures ffmpeg can produce without
#              a real sampled asset

@dataclass(frozen=True)
class _ToneSpec:
    shape: str  # "tone" | "sweep" | "burst"
    freq_low: float
    freq_high: float | None = None  # for "sweep": start freq; freq_low is end freq if descending
    duration_s: float = 0.25
    bandpass_width: float | None = None  # for "burst"


_TONE_SPECS: dict[SfxCategory, _ToneSpec] = {
    SfxCategory.CASCADE_PAYOFF: _ToneSpec("sweep", freq_low=400, freq_high=1200, duration_s=0.4),  # genuine rising riser
    SfxCategory.MONEY: _ToneSpec("tone", freq_low=1200, duration_s=0.25),  # unchanged from prior pass
    SfxCategory.PSYCHOLOGY_TERM: _ToneSpec("tone", freq_low=500, duration_s=0.35),  # soft, lower, longer fade = "soft pulse"
    SfxCategory.STUDY_STAT: _ToneSpec("tone", freq_low=1600, duration_s=0.12),  # quick high chime, distinct from psych pulse
    SfxCategory.CLASSIFIED: _ToneSpec("burst", freq_low=300, bandpass_width=200, duration_s=0.2),  # paper-rustle-ish + low thud character via bandpass center
    SfxCategory.COVERUP: _ToneSpec("tone", freq_low=100, duration_s=0.4),  # low, slow, moody
    SfxCategory.NEURO_TERM: _ToneSpec("tone", freq_low=900, duration_s=0.1),  # sharp/fast high blip -- distinct from CH1's soft low pulse
    SfxCategory.MEMORY: _ToneSpec("sweep", freq_low=900, freq_high=300, duration_s=0.3),  # falling = "reverse riser"/glitch
    SfxCategory.DATE_EVENT: _ToneSpec("burst", freq_low=800, bandpass_width=400, duration_s=0.15),  # mechanical click-ish (film-reel/page-turn), different band than CH3's rustle
    SfxCategory.LOST_TO_HISTORY: _ToneSpec("tone", freq_low=220, duration_s=0.6),  # long slow swell
    SfxCategory.SCALE_DISTANCE: _ToneSpec("burst", freq_low=70, bandpass_width=60, duration_s=0.5),  # deep rumble
    SfxCategory.DISCOVERY: _ToneSpec("burst", freq_low=2500, bandpass_width=1500, duration_s=0.15),  # radio-static-ish blip, high band
    SfxCategory.TWIST: _ToneSpec("tone", freq_low=220, duration_s=0.25),
    SfxCategory.HOOK_OPENER: _ToneSpec("tone", freq_low=1800, duration_s=0.25),
}


def generate_placeholder_tone(category: SfxCategory, out_path: Path) -> None:
    """Synthesizes a labeled placeholder cue -- NOT a real SFX asset. See
    module docstring for why, and for what's NOT_SOURCED about
    normalization."""
    spec = _TONE_SPECS[category]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fade_d = spec.duration_s * 0.6

    if spec.shape == "tone":
        filter_complex = f"sine=frequency={spec.freq_low}:duration={spec.duration_s}"
        af = f"afade=t=out:st=0:d={fade_d}"
        cmd = [ffmpeg_path(), "-y", "-f", "lavfi", "-i", filter_complex, "-af", af, str(out_path)]
    elif spec.shape == "sweep":
        # Genuine linear frequency sweep via aevalsrc, not a fixed tone.
        f0, f1 = spec.freq_low, spec.freq_high
        expr = f"sin(2*PI*t*({f0}+({f1}-{f0})*t/{spec.duration_s})/2)"
        cmd = [
            ffmpeg_path(), "-y", "-f", "lavfi",
            "-i", f"aevalsrc={expr}:d={spec.duration_s}",
            "-af", f"afade=t=out:st=0:d={fade_d}",
            str(out_path),
        ]
    elif spec.shape == "burst":
        center = spec.freq_low
        width = spec.bandpass_width or center
        cmd = [
            ffmpeg_path(), "-y", "-f", "lavfi",
            "-i", f"anoisesrc=color=white:duration={spec.duration_s}",
            "-af", f"bandpass=f={center}:width_type=h:w={width},afade=t=out:st=0:d={fade_d}",
            str(out_path),
        ]
    else:
        raise ValueError(f"unknown tone shape {spec.shape!r}")

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"ffmpeg placeholder cue generation failed ({category.name}):\n{result.stderr}")
